const postTypes = {
  GET_POSTS: "GET_POSTS",
  GET_POSTS_START: "GET_POSTS_START",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_FAIL: "GET_POSTS_FAIL",

  ADD_POST: "ADD_POST",
  ADD_POST_START: "ADD_POST_START",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_FAIL: "ADD_POST_FAIL",

  GET_USER_POSTS: "GET_USER_POSTS",
  GET_USER_POSTS_START: "GET_USER_POSTS_START",
  GET_USER_POSTS_SUCCESS: "GET_USER_POSTS_SUCCESS",
  GET_USER_POSTS_FAIL: "GET_USER_POSTS_FAIL",

  DELETE_POST: "DELETE_POST",
  DELETE_POST_START: "DELETE_POST_START",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAIL: "DELETE_POST_FAIL",

  UPDATE_POST: "UPDATE_POST",
  UPDATE_POST_START: "UPDATE_POST_START",
  UPDATE_POST_FAIL: "UPDATE_POST_FAIL",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
};

export default postTypes;
