const userTypes = {
  USER_SIGNUP: "USER_SIGNUP",
  USER_SIGNUP_START: "USER_SIGNUP_START",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAIL: "USER_SIGNUP_FAIL",

  USER_SIGNIN: "USER_SIGNIN",
  USER_SIGNIN_START: "USER_SIGNIN_START",
  USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAIL: "USER_SIGNIN_FAIL",

  USER_LOGOUT: "USER_LOGOUT",
  CHECK_LOGIN: "CHECK_LOGIN",
};

export default userTypes;
